######################################################################
# Automatically generated by qmake (2.01a) ter jun 1 18:26:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT = core gui network

# Input
HEADERS += server.h
SOURCES += main.cpp server.cpp
