######################################################################
# Automatically generated by qmake (2.01a) ter jun 1 18:21:07 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT = core gui network

# Input
SOURCES += main.cpp
