######################################################################
# Automatically generated by qmake (2.01a) ter jun 1 18:29:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT = core gui network

# Input
HEADERS += client.h
SOURCES += client.cpp main.cpp
