######################################################################
# Automatically generated by qmake (2.01a) mié may 12 12:01:58 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += p.cpp

QT+=sql
