######################################################################
# Automatically generated by qmake (2.01a) mié may 12 13:44:03 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MysqlConection.h
SOURCES += MysqlConection.cpp p.cpp
QT+=sql
