######################################################################
# Automatically generated by qmake (2.01a) dom may 2 14:56:11 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += p.cpp

#Agregado por VARG
#QT += sql